import { BaseModel } from "src/app/shared/models/base-model";

export interface MerchantModel extends BaseModel {
    email: string,
    phoneNumber: string,
    companyName: string,
    companyType: string,
    responsiblePersonLastName: string,
    responsiblePersonFistName: string,
    registrationCertificateFilePath: string,
    passportFilePath: string,
    transportationCertificateFilePath: string,
    logoFilePath: string,
    notes: string,
    mfo: string,
    inn: string,
    oked: string,
    dunsNumber: string,
    ibanNumber: string,
    supervisorFirstName: string,
    supervisorLastName: string,
    legalAddress: string,
    factAddress: string,
    bankName: string,
    taxPayerCode: string,
    responsbilePersonPhoneNumber: string,
    verified: boolean,
    rejected: boolean,
    rejectedAt: string,
    verifiedBy: string,
    verifiedAt: Date,
    createdAt: Date,
    completed: boolean,
    active: boolean,
    blocked?: boolean,
    bankAccounts: [{id: number,account:string, currency: {id: number, code: string, name: string}}],
    balances?: [{activebalance: number}],
    user:any;
}