export enum Permission {
  SendPush = 'sendPush',
  Chat = 'chat',
  TrackingPage = 'trackingPage',

  AdminsPage = 'adminsPage',
  AdminCreate = 'adminCreate',
  AdminUpdate = 'adminUpdate',
  AdminDelete = 'adminDelete',

  DriversPage = 'driversPage',
  DriverTopUpBalance = 'driverTopUpBalance',
  DriverCreate = "driverCreate",
  DriverUpdate = "driverUpdate",
  DriverDelete = "driverDelete",
  DriverDetail = "driverDetail",
  DriverBlock = "driverBlock",
  DriverAddTransport = "driverAddTransport",
  DriverPush = "driverPush",
  DriverAddSubscribe = "driverAddSubscribe",

  ClientsPage = 'clientsPage',
  ClientCreate = 'clientCreate',
  ClientUpdate = 'clientUpdate',
  ClientDetail = 'clientDetail',
  ClientDelete = 'clientDelete',
  ClientPush = 'clientPush',

  ServicesPage = 'servicesPage',
  ServiceCreate = 'serviceCreate',
  ServiceDetail = 'serviceDetail',
  ServiceStatusChange = 'serviceStatusChange',
  ServiceLog = 'serviceLog',
  ServiceChat = 'serviceChat',

  GsmPage = 'gsmPage',
  GsmTopUpBalance = 'gsmTopUpBalance',
  GsmCardManagment = 'gsmCardManagment',

  OrdersPage = 'ordersPage',
  OrderCreate = 'orderCreate',
  OrderUpdate = 'orderUpdate',
  OrderDetail = 'orderDetail',
  OrderOffers = 'orderOffer',
  OrderCancel = 'orderCancel',
  OrderAssignDriver = 'orderAssignDriver',
  OrderSendOfferToDriver = 'orderSendOfferToDriver',
  OrderChangeStatus = 'orderChangeStatus',

  TmsesPage = 'tmsesPage',
  TmsDetail = 'tmsDetail',
  TmsUpdate = 'tmsUpdate',
  TmsDriversList = 'tmsDriversList',
  TmsTransactionsHistory = 'tmsTransactionsHistory',
  TmsTopupBalance = 'tmsTopupBalance',
  TmsBlock = 'tmsBlock',
  TmsRequstsList = 'tmsRequstsList',

  MerchantsPage = 'merchantsPage',

  DashboardPage = 'dashboardPage',
  ArchivePage = 'archivePage',
  DriverServicesPage = 'driverServicesPage',
  RolesPage = 'rolesPage',
  LoadingMethodsPage = 'loadingMethodsPage',
  SubscriptionTypesPage = 'subscriptionTypesPage',
  CurrenciesPage = 'currenciesPage',
  TransportTypesPage = 'transportTypesPage',
  TransportKindsPage = 'transportKindsPage',
  CargoStatusPage = 'cargoStatusPage',
  CargoPackagesPage = 'cargoPackagesPage',
  ServiceStatusPage = 'serviceStatusPage',
  CargoTypeGroupsPage = 'cargoTypeGroupsPage',
  CargoTypesPage = 'cargoTypesPage',

  AnaliticsPage = 'analiticsPage',
}