export enum Permission {
    SendPush = 'sendPush',
    Chat = 'chat',
    TrackingPage = 'trackingPage',
   
    AdminsPage = 'adminsPage',
    AdminCreate = 'adminCreate',
    AdminUpdate = 'adminUpdate',
    AdminDelete = 'adminDelete',

    DriversPage = 'driversPage',
    DriverTopUpBalance = 'driverTopUpBalance',
    DriverCreate = "driverCreate",
    DriverUpdate = "driverUpdate",
    DriverDelete = "driverDelete",
    DriverDetail = "driverDetail",
    DriverBlock = "driverBlock",
    DriverAddTransport = "driverAddTransport",
    DriverPush = "driverPush",
    
    ClientsPage = 'clientsPage',
    ClientCreate = 'clientCreate',
    ClientUpdate = 'clientUpdate',
    ClientDetail = 'clientDetail',
    ClientDelete = 'clientDelete',
    ClientPush = 'clientPush',

    ServicesPage = 'servicesPage',
    ServiceCreate = 'serviceCreate',
    ServiceDetail = 'serviceDetail',
    ServiceStatusChange = 'serviceStatusChange',
    ServiceLog = 'serviceLog',
    ServiceChat = 'serviceChat',

    TmsesPage = 'tmsesPage',
    TmsDetail = 'tmsDeatil',

    MerchantsPage = 'merchantsPage',
    DashboardPage = 'dashboardPage',
    ArchivePage = 'archivePage',
    OrdersPage = 'ordersPage',
    DriverServicesPage = 'driverServicesPage',
    GsmPage = 'gsmPage',
    RolesPage = 'rolesPage',
    LoadingMethodsPage = 'loadingMethodsPage',
    SubscriptionTypesPage = 'subscriptionTypesPage',
    CurrenciesPage = 'currenciesPage',
    TransportTypesPage = 'transportTypesPage',
    TransportKindsPage = 'transportKindsPage',
    CargoStatusPage = 'cargoStatusPage',
    CargoPackagesPage = 'cargoPackagesPage',
    ServiceStatusPage = 'serviceStatusPage',
    CargoTypeGroupsPage = 'cargoTypeGroupsPage',
    CargoTypesPage = 'cargoTypesPage',
    

  }